default: &default
  adapter: postgresql
  encoding: unicode
  database: budgetapp_development
  pool: 5
  host: localhost
  username: postgres

development:
  <<: *default
  database: budgetapp_development

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: budgetapp_test
  pool: 5
  username: postgres

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: budgetapp_production
  username: postgres
